

#ifndef ERROR_H
#define ERROR_H

typedef enum {
    E2S_OK = 0,

    /* CLI parsing/commands */
    E2S_ERR_CLI_EMPTY_LINE,
    E2S_ERR_CLI_UNKNOWN_COMMAND,
    E2S_ERR_CLI_USAGE_SET,
    E2S_ERR_CLI_USAGE_GET,
    E2S_ERR_CLI_USAGE_PININFO,
    E2S_ERR_CLI_UNKNOWN_PIN,
    E2S_ERR_CLI_PIN_INPUT_ONLY,
    E2S_ERR_CLI_LINE_FORMAT,
    E2S_ERR_CLI_LINE_TRUNCATED,

    /* Event queue */
    E2S_ERR_EVENT_QUEUE_FULL,
    E2S_ERR_EVENT_QUEUE_EMPTY,

    /* PIO TX/RX driver */
    E2S_ERR_PIO_UNAVAILABLE,
    E2S_ERR_PIO_RX_EMPTY,
    E2S_ERR_PIO_TX_FULL,

    /* HDLC encoder */
    E2S_ERR_HDLC_ENCODE_INVALID_ARGS,
    E2S_ERR_HDLC_ENCODE_FRAME_TOO_SMALL,
    E2S_ERR_HDLC_ENCODE_FRAME_NOT_EMPTY,
    E2S_ERR_HDLC_ENCODE_OVERFLOW,

    /* HDLC decoder */
    E2S_ERR_HDLC_DECODE_INVALID_ARGS,
    E2S_ERR_HDLC_DECODE_INVALID_FRAME,
    E2S_ERR_HDLC_DECODE_PAYLOAD_TOO_LONG,
    E2S_ERR_HDLC_DECODE_PAYLOAD_TOO_SHORT,
    E2S_ERR_HDLC_DECODE_CRC_MISMATCH,

    /* W5500 */
    E2S_ERR_W5500_INIT_FAILED,
    E2S_ERR_W5500_SOCKET_OPEN_FAILED,
    E2S_ERR_W5500_SEND_FAILED,
    E2S_ERR_W5500_RECV_FAILED
} e2s_error_t;

#endif /* ERROR_H */
